version: "3.8"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 27017:27017
    restart: unless-stopped
  nodejs:
    container_name: nodejs
    build: ./
    image: nodejs
    ports: 
      - 8080:8080
    restart: always